# Generated by Django 3.0.4 on 2020-07-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_blog_like_number'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='post_like',
            field=models.ManyToManyField(blank=True, related_name='like_user', to='main.Blog'),
        ),
    ]
