# Generated by Django 3.0.4 on 2020-07-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='like_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
